-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jun 02, 2020 at 10:52 AM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `scholarship_portal1`
--

-- --------------------------------------------------------

--
-- Table structure for table `scholarship_portal2020_db`
--

CREATE TABLE `scholarship_portal2020_db` (
  `name` varchar(152) NOT NULL,
  `details` varchar(906) DEFAULT NULL,
  `incentives` varchar(636) DEFAULT NULL,
  `link` varchar(344) DEFAULT NULL,
  `tags` varchar(43) DEFAULT NULL,
  `international` int(1) DEFAULT 0,
  `national` int(1) DEFAULT 0,
  `merit` int(1) DEFAULT 0,
  `girls` int(1) DEFAULT 0,
  `scst` int(1) DEFAULT 0,
  `bs` int(1) DEFAULT 0,
  `first` int(1) DEFAULT 0,
  `final` int(1) NOT NULL DEFAULT 0,
  `minority` int(1) DEFAULT 0,
  `special` int(1) DEFAULT 0,
  `financial` int(1) DEFAULT 0,
  `sports` int(1) DEFAULT 0,
  `highed` int(1) DEFAULT 0,
  `state` int(1) DEFAULT 0,
  `research` int(1) DEFAULT 0,
  `exchange` int(1) DEFAULT 0,
  `ent` int(1) NOT NULL DEFAULT 0,
  `allent` int(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `scholarship_portal2020_db`
--

INSERT INTO `scholarship_portal2020_db` (`name`, `details`, `incentives`, `link`, `tags`, `international`, `national`, `merit`, `girls`, `scst`, `bs`, `first`, `final`, `minority`, `special`, `financial`, `sports`, `highed`, `state`, `research`, `exchange`, `ent`, `allent`) VALUES
(' Chief Minister fellowship Yojana (CMFY)', 'Student must have domicile in Jharkhand   Parents who are not income tax payee ', 'Refer the website for details ', 'http://jhcmfellowship.nic.in', 'State based scholarships \r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1),
(' Gunwan vidyarthi Aarthik Sahayya Yojana', 'Refer the website for details ', 'Refer the website for details ', 'https://mahadbtmahait.gov.in', 'State based scholarship\r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1),
(' Nanyang Technological University - University Scholars Programme\n', 'Refer to the website for further details \n', 'Refer to the website for further details \n', 'http://www.ntu.edu.sg/USP/partners/Pages/STEP-Youth-Regional-Affairs-Dialogue-2019.aspx\n', 'international\r', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
(' S.N. Bose Scholars Program', 'Indian citizens currently pursuing a Bachelors or Masters\' degree at a recognized institution of higher education and learning in India\nOpen to students of Atmospheric and Earth Sciences; Chemical Sciences; Engineering Sciences; Mathermatical and Computational Sciences; and Physical Sciences.', 'Refer the website for details ', 'http://iusstf.org/assets/sitesfile/image/download_links/pdf/pdf_1300705100.pdf', 'Exchange program \r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1),
(' Shastri Indo-Canadian Institute', 'Refer the website for details ', 'Refer the website for details ', 'https://www.shastriinstitute.org/sites/default/files/PriorityAreasDocument.pdf\nhttps://www.shastriinstitute.org/grants-awards-and-opportunities-for-indian-canadian-scholars\nhttps://www.shastriinstitute.org/', 'Research and internship in Canda \r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1),
('AICTE Pragati Saksham Scholarship', 'Specially Abled Student, having disability of not less than 40% and family income not more than 8 lakh per annum during the preceding financial year (in case of married girl, the income of parents/in-laws, whichever is higher will be considered)\nRefer to the website for further details ', 'Refer to the website for further details \nRefer to the website for further details ', 'https://www.aicte-pragati-saksham-gov.in/\nThe selection of candidate will be made on merit on the basis of qualifying examination to peruse the respective Technical Degree/Diploma course from any of the AICTE approved institution', 'girls + financial constraint\r', 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1),
('BIRAC BIG Scheme', 'The BIG scheme of BIRAC was launched in June 2012 and it is open to individuals (graduates in any discipline, research scholars, faculties, doctors, scientists, etc.), Innovators, and start-ups (incorporated after 1st July, 2015).', ' The scheme enables technology innovators and entrepreneurs in the healthcare/ medical devices/agriculture domain to pursue a promising technology idea, establish and validate proof of concept (POC) for their idea - http://www.birac.nic.in/desc_new.php?id=406 .  As part of this scheme, successful applicants can receive up to INR 50 lakh for research projects with commercialization potential, for duration of up to 18 months. ', 'www.birac.nic.in                                                               If you wish to discuss about your idea, you can visit SINE office on the 3rd Floor of CSRE Building, IIT Bombay Campus. For help with the application process, please contact Dr. Shraddha Chauhan at SINE (shraddha@sineiitb.org).', 'international\r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1),
('Birmingham International Summer School', 'Refer to the website for further details ', 'Refer to the website for further details ', 'Nomination through IITB.', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Canadian Government 2017 Banting Postdoctoral Fellowship', 'The Banting Postdoctoral Fellowships program provides funding to the very best postdoctoral applicants, both nationally and internationally, who will positively contribute to the country\'s economic, social and research-based growth.', 'Fellowships will be valued at $70,000 per year (taxable) for 2 years. The program will fund 70 new fellowships distributed equally across NSERC, SSHRC and CIHR.', '<http://banting.fellowships-bourses.gc.ca/en/home-accueil.html>', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Cargill global scholars program', 'Should be Indian Citizen \nA second year student in IIT Bombay/Delhi/Gandhinagar or Delhi Technological University or National Institute of Technology Tiruchirappalli \nShould demonstrate exemplary academic performance and leadership skills', 'Chance to attend fully funded two conferences one at global level and at national level among other Cargill scholars and Cargill employees\nScholarship benefits include scholarship award of up to $5000 ($2,500 USD annually for up to two years), access to leadership and enrichment activities and networking opportunities, academic and professional guidance from a Cargill leader and participation in a community of future global leaders.', 'http://www.cargillglobalscholars.com', 'merit based \r', 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Central Sector Scholarship Scheme of Top Class Education for SC students', 'The student must be a scheduled caste \nThe net family income from all the sources must not be greater than 6 lakhs', 'Full tuition fee and non-refundable charges\nLiving expenses to the beneficiary @2220/- per month per student\nBooks and stationary @ Rs. 3000/- per annum per student\nA latest computer/laptop of reputed brand with accessories like UPS and printer limited to Rs. 45000/- per student as one time assistance during the course', 'https://scholarships.gov.in', 'SC/ST students (minority)\r', 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Charpak Exchange Scholarship ', 'Refer to the website for further details ', 'Refer to the website for further details ', 'http://www.inde.campusfrance.org/en/page/charpak-exchange-program-spring-session-0', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Chinese Government Scholarship', 'Refer to the website for further details ', 'Refer to the website for further details ', 'https://lists.iitb.ac.in/pipermail/student-notices/attachments/20170322/a214398e/attachment.pdf', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Circular for Central Sector Scholarship Scheme of Top Class Education for SC ST', 'Students who are above 80th percentile of successful candidates in the relevant stream from the respective Board of Examination in Class XII of 10+2 pattern or equivalent and pursuing regular courses (not correspondence or distance mode) in Colleges/Institutions recognized by All India Council of Technical Education, UGC Act, 1956, Medical Council of India, Dental Council of India and respective regulatory authorities and not availing benefit of any other scholarship scheme including State run scholarship schemes/Fee waiver and reimbursement scheme are eligible under the scheme. Students pursuing Diploma courses are not eligible under the scheme. Refer the document for further details', 'refer the document for further details ', 'https://scholarships.gov.in', 'merit based for all\r', 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Commonwealth Scholarship and Fellowship', 'The Commonwealth Scholarship and Fellowship Plan (CSFP) is an international programme under which Commonwealth countries offer scholarships and fellowships to citizens of other member state. The CSFP is aimed at students of Commonwealth countries who can make a significant contribution to their home country after the completion of a higher education programme in the UK.', ' Eligible candidates can only apply either for one year Taught Master\'s courses or PhD degree. Subjects covered are Engineering and Technology, Science (Pure and Applied), Agriculture, Humanities and Social Sciences.', 'http://proposal.sakshat.ac.in/scholarship/', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Commonwealth Scholarship in the UK', 'Refer to the website for further details ', 'Refer to the website for further details ', 'https://fs29.formsite.com/m3nCYq/form62/form_login.html\nhttp://proposal.sakshat.ac.in/scholarship/', 'international\r', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('DAAD Scholarship', 'Refer to the website for further details ', 'Refer to the website for further details ', 'https://www.daad.in/en/', 'international\r', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Dorilal agarwal scholarship for meritorious specially challenged students', 'Refer the website for details ', 'Refer the website for details ', 'Apply through IITB                                       https://goo.gl/LyBMrh', 'Specially challenged students \r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1),
('EIL Scholarship for SC & ST students', 'Refer to the website for further details ', 'Refer to the website for further details ', 'http://lists.iitb.ac.in/pipermail/student-notices/attachments/20180914/2d852633/attachment.pdf                                    Apply through IIT B Academic office', 'national\r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Fair and Lovely Foundation', 'Women between 15-30 years who wish to pursue undergraduate or post graduate courses. \nCandidates who have passed 12th standard securing a minimum of 60% in 10th and 12th Std board exams', 'Refer to the website for further details ', 'https://www.fairandlovelyfoundation.in/scholarship', 'girls', 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Foundation for Academic Excellence and Access (FAEA)', 'Students who have passed Class XII from a recognized Board of Secondary Education in India or 1st year under-graduate students on roll Students belonging to socially and economically disadvantaged sections (SC/ST/BPL Category). Further we have some special scholarships for Girls Students belonging to socially and economically disadvantaged section in the BPL category from Karnataka, Kerala, Maharashtra, Tamil Nadu.  In addition we have some need cum merit based financial grants for General Category students especially for those students who have obtained above 90% marks in their Higher Secondary Exam and/or have been able to get admission in the first rate Institutions of Excellence in the country.', '-Tuition fee, maintenance allowance or hostel and mess charges as per our norms.', 'http://www.faeaindia.org/Adv2019.pdf', 'girls + minority + merit based \r', 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Future Research Talent’ (FRT) travel award program floated by the Australian National University (ANU)', 'Refer to the website for further details ', 'The FRT travel award (AUD 6000) is offered by the ANU College of Science and ANU College of Health and Medicine to students from India and the scheme will provide for fully-funded, 3-month research experiences at ANU in the fields of science, health & medicine.', 'https://science.anu.edu.au/study/scholarships/future-research-talent-travel-awards-india', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Gunwan Vidyarthi Aarthik Sahayya Yojana', 'Refer the website for details ', 'Refer the website for details ', 'www.mahadbtmahait.gov.in', 'State Scholarship \r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1),
('Hindustan Times, Panasonic', 'Hindustan Times & Panasonic conducts a yearly scholarship program for IIT students which covers tuition fees of 30 students for all 4 years. ', 'Scholarship Assistance of INR 42,500 per year per student for four years to cover the tuition fees.', 'rattichhatrscholarship.shine.com', 'Financial constraint\r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1),
('Honda Yes Award', 'Student of the Fifth semester\nAggregate CGPA over & above 7.00 by the end of semester lV\nCleared the first four semesters without any backlogs', 'Each Y-E-S Award recipient will receive USD 3,000 (US Dollar Three Thousand only) in equivalent Indian Rupees.\nEvery Y-E-S Award recipient becomes eligible for the Y-E-S Award Plus, an additional award, if, within four years after he/she received the Y-E-S Award prize.A credit-granting internship program offered by a Japanese company or research institute\'s summer program for two and half months.Internship participants will receive US$ 7,000 for internship in Japan + US$ 3,000 preparation fees for further study in Japan (10 weeks) for Y-E-S Plus. OR USD 10,000 for Post-Graduation studies in Japan (1~2 years) as Y-E-S Award Plus.', '', 'none \r', 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Huayu Enrichment scholarship ', '“Huayu Enrichment scholarship” for students want to learn Mandarin Chinese, and also “Taiwan scholarship” for these who want to study for a degree', 'Refer to the website for further details ', 'https://www.roc-taiwan.org/in_en/cat/9.html', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('ILDP Onsite Training at Hiroshima University', 'Applying student must be a post graduate', 'Refer to the website for further details ', 'Maximum 2 post graduate (Master and PhD) students will be nominated to Hiroshima University by IITB.', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('ILDP Study Abroad Program\'', 'Refer to the website for further details ', 'The ILDP Study Abroad Program\' is a research program with Hiroshima University (HU), Japan for a mobility of minimum of 2 weeks to maximum 6 months. The students will have to travel before March 2019. This program aims to invite IITB Undergraduate students, Masters and Doctoral students for research work.', 'IITB nominates some people on the basis of SOP, and other details, and HU carries out the further selection process.http://www.ildp.hiroshima-u.ac.jp/entry-course/ildp-study-abroad-program/ildp-study-abroad-program-2018-2019', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
('Indian Oil Sports Scholarship', 'Those who are representing/have represented the country in team games. Age: 14-19 Years\nThe sports scholarships to be awarded will be for the following games : Athletics, badminton, chess, cricket, golf, hockey, table tennis, snookers & billiards and various other games. In \'Other Games\' the category of games will be Basketball, Volleyball, Archery, Boxing, Carrom, Gymnastics, Kabaddi, Shooting, Swimming, Wrestling and any other game (with medal prospect). The application will be routed through and recommended by Appropriate Authority / Institution (such as Head / Principal of Institution / School) along with certified copy of standing of sports scholar in appropriate National / State level issued by concerned Sports Authority. All sports scholarships will be for a period of three years and will be discontinued during the tenure, in case the performance of the player is not found satisfactory.', 'Scholar - per month 9000 (1st year) 10000 (2nd year) 11000 (3rd year) Elite Scholar - 12000 (1st year) 13000 (2nd year) 14000 (3rd year)', 'https://www.iocl.com/AboutUs/IndianOilSports.aspx', 'Sports, only for 19 years of age', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1),
('INSPIRE (SHE) – Scholarship for Higher Education', 'Applicant should be pursuing a three year course in basic/natural sciences such as B.Sc, B.Sc (Honours), four year B.S or five year integrated B.Sc-M.Sc or BS-MS programme from any recognized college/ University in India. The applicants must come within the top one per cent fixed for each state or Central Board Examination for the year. Those who are among the top 10,000 rank in various national level entrance examinations such as JEE(mains), JEE (advanced), NEET for medical and IISERS may also apply.', 'Candidate will receive Rs. 80,000 per year. The scheme covers the following subjects under the basic/natural sciences: Physics, Chemistry, Mathematics, biology, Statistics, Geology, Astrophysics, Astronomy, Electronics, Botony, Zoology, Bio-chemistry, Anthropology, Microbiology, Geophysics, Geochemistry, Atmospheric Science and oceanic Sciences. Courses other than these subjects such as engineering and medicine are not under the scope of this programme. As part of the scheme, students shall be required to undertake research projects every year in any recognized research centres across India or abroad.', 'http://www.inspire-dst.gov.in/', 'BS Students', 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('J. N. Tata Scholarship', 'The final selection of candidates depends on their performance at their interview, score at the online test and score based on academic results, GRE/GMAT/IELTS/TOEFL scores, extra-curricular activities, research work, and statement of purpose and work experience.', 'The J. N. Tata Endowment awards a one-time loan scholarship to Indian nationals at the beginning of their academic year for full time Postgraduate/Ph.D./Postdoctoral studies/Research Fellowshipsabroad, in all fields, irrespective of caste, creed, gender or community. The amount to be awarded to each scholar by way of loan scholarship is determined on the basis of the norms laid down for the purpose, and does not cover the full cost of studies. The amount awarded as the loan scholarship ranges between Rs.1,00,000/- and Rs.10,00,000/-. All selected scholars do not necessarily qualify for the maximum amount.', 'www.jntataendowment.org', 'Higher education (India as well as abroad)\r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
('Japanese Government [MEXT] Scholarship Program 2019 for Research Students', 'Refer to the website for further details ', 'Refer to the website for further details ', 'www.mhrd.gov.in/scholarships', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Japanese Government [MEXT] Scholarship Program 2019 for undergraduate students, college of technology students and specialized training college students', 'Refer to the website for further details ', 'Refer to the website for further details ', 'www.mhrd.gov.in/scholarships', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('KTH INDIA Scholarship', 'Refer to the website for further details ', 'Refer to the website for further details ', 'https://www.kth.se/en/studies/master/scholarships/kth-scholarship-1.72827', 'international\r', 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Loreal India for Young Women in Science Scholarship', 'Passed standard XII (Science) from India, Minimum 85% in PCB / PCM, Maximum 19 years of age as on May 31st .\nMust be a girl', 'The scholarship is only for girl students and consists of up to Rs. 2.5 lacs, granted in equal annual instalments over the period of the degree of study,', 'Shortlisted candidates and their parents will be called to attend an interview in Mumbai/ Delhi/ Bangalore/ Hyderabad/ Kolkata (based on the proximity of the candidate) at their own cost. The interview will be conducted by a jury consisting of eminent members of the scientific and academic communities along with L\'Oréal India representatives.', 'girls', 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('lovakia / Scholarships for PhD students, university teachers, researchers and artists (Incoming & Outgoing)', 'Refer to the website for further details ', 'Refer to the website for further details ', 'https://www.scholarships.sk/en/', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Mahabir Prasad Singh Foundation for Education and Research Scholarship', 'Refer the website for details ', 'Refer the website for details ', 'http://lists.iitb.ac.in/pipermail/student-notices/attachments/20180914/b3a956fa/attachment.pdf                                                         Apply through IIT B academic office', 'national\r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Marie Curie Post-doctoral Research Fellowships (RESPIRE 3)', 'Refer to the website for further details ', 'Refer to the website for further details ', 'https://www.ersnet.org/professional-development/fellowships/marie-curie-post-doctoral-research-fellowships-(respire-3)', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Maulana Azad National Scholarship', 'The scholarship aims to provide integrated five year fellowships in the form of financial assistance to students from minority communities to pursue higher studies such as M. Phil and Ph.D. The Fellowship will cover all Universities/Institutions recognized by the UGC. 30% of the fellowship shall be earmarked for women students; remaining 70% will be general.\nRefer to the website for further details ', 'Refer to the website for further details \nRefer to the website for further details ', 'Selection of the minority students for award of fellowship under the Scheme will be made on the basis of merit in National Eligibility Test (NET) of UGC conducted by Central Board of Secondary Education (CBSE) and CSIR.\nhttp://www.minorityaffairs.gov.in/schemesperformance/maulana-azad-national-fellowship-minority-students-scheme', 'Minority + Higher Education in India\r', 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1),
('MCM Scholarship', '', '', 'https://scholarships.gov.in/public/schemeGuidelines/MoMA_MCM_2018-20.pdf', 'SC/ST minority based \r', 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('MEXT Scholarship', 'Applicants must have the GPA larger than 2.30 (on a grade point scale of 4) in the latest 2 academic years\nRequired language ability: TOEFL >= 72, IE >= IELTS, JLPT >= N2 etc.\nApplicants to other MEXT scholarships (at any other Japanese universities or embassies) cannot apply to this program\nApplicants must receive an acknowledgement from their prospective supervising professors of UTokyo before the application deadline.\n Applicants must be able to receive a recommendation letter from the Dean, President or their equivalent of their latest institution before the end of January.', 'Scholarship: 147,000 Yen/ Month (Master Students who are at Hongo and Komaba Campus)\n148,000 Yen/ Month (Doctoral Students who are at Hongo and Komaba Campus)\nTuition fee and Admission fee\n Air ticket to Japan (and air ticket back to home countries if the students return home after the graduation)', 'https://drive.google.com/open?id=1Gykb9ykGi0G10urbx_6w_vGUjTi3YdC6', 'international\r\n+ Merit', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('MOBILITY GRANTS for BACHELOR STUDENTS FROM INDIAN PARTNER UNIVERSITIES to A4U UNIVERSITIES', 'Refer to the website for further details ', 'Refer to the website for further details ', 'http://alliance4universities.', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Narotam Sekhsaria Scholarships for Final year Engineering students', 'Refer to the website for further details ', 'Refer to the website for further details ', 'https://pg.nsfoundation.co.in/Scholarship2018/?isFrom=Paid&utm_medium=CPC&utm_campaign=NSF_Desktop_Brand_BMM&utm_adgroup=ns_foundation_co_in&utm_term=%2Bns%20%2Bfoundation&gclid=Cj0KCQiAtvPjBRDPARIsAJfZz0pLUDgvmewit3IdsCYCP4JXhVxfxxCvEKTjDPZsBCNnh-NUqjI-qIEaAs4vEALw_wcB', 'national\r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Narotam Sekhsaria Scholarships for Higher Studies', 'Indian nationals Students below 30 years of age as on January 31, 2020 Graduates of an accredited Indian University (students in the final year of the degree course, or those awaiting results are also eligible) Students planning to pursue postgraduate studies at top ranking institutions from Fall 2020 Students who have applied and are awaiting an acceptance from the university are also eligible to apply. The award of scholarship is subject to securing admission', 'The selected scholars may also be recommended for a gift scholarship based on their overseas academic performance and partial travel assistance from our allied Trusts as may be decided at the sole discretion of the Trustees of the concerned Trusts. A gift scholarship can be for a maximum amount of Rs.7,50,000/- and the partial travel grant can be a maximum of Rs.50,000/-.', 'http://pg.nsfoundation.co.in/', 'Higher education (India as well as abroad)\r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
('OP Jindal Engineering and Management Scholarships', 'First three toppers of 1st, 2nd, 3rd, and 4th year students of the following streams of engineering:\na. Civil Engineering\nb. Electrical Engineering\nc. Mechanical Engineering\nd. Metallurgical Engineering\nThe eligibility criteria for the 1st year students will be the entrance exam ranking considered by college at the time of the admission.\nThe eligibility criteria for the 2nd, 3rd, and 4th year students will be based on the academic performance of the previous year.', 'Engineering - INR 80,000 per Student', 'http://www.opjems.com/eligibilityCriterion.html', 'merit \r', 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Panasonic Scholarship Programme', 'Refer to the website for further details ', 'Refer to the website for further details ', 'http://rattichattrscholarship.shine.com', 'national\r', 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Pragati Scholarship', 'Must be a girl\nThe candidate should be admitted to 1st year of Degree/Diploma course in any of the AICTE approved Institution. \nTwo girl children per family are eligible, whose family income is not more than 8 lakh per annum.\nIn case of married girl, the income of parents/in-laws, whichever is higher will be considered. The selection of candidate will be made on merit on the basis of qualifying examination to peruse the respective Technical Degree/Diploma course from any of the AICTE approved institution.', 'Tuition Fee of Rs. 30,000/- or actual, whichever is less and Rs.2000/- per month for 10 months as incidental charges each year in case of Tuition fee waiver/reimbursement\nStudents are eligible to get an amount of Rs. 30,000/- for the purchase of books/Equipment/Softwares/Laptop/Desktop/Vehicle/ Fee paid towards competitive examination applications forms/exam.\nRefer to the website for further details ', 'https://www.aicte-pragati-saksham-gov.in/', 'girls ', 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Prerana', 'Refer to the website for further details ', 'This scheme aims at providing financial support to institutes who are willing to put extra efforts for encouraging and training SC/ST students for GATE/GPAT/CAT/CMAT and GRE.', 'http://www.aicte-india.org/user/login', 'SC/ST students ', 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Rhodes Scholarship for India', 'Refer to the website for further details ', 'Since 1902, the Rhodes Scholarship programme has served as a symbol of excellence worldwide, producing individuals who have changed the world. Rhodes Scholars have gone on to become heads of state, Pulitzer Prize winning authors, Nobel Prize winners and Olympians.', 'http://www.rhodeshouse.ox.ac.uk/india   <http://rhodestrust.cmail20.com/t/r-l-jlllijn-huujmlhlt-j/>', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('RWTH Scholarship ', 'Highly qualified female engineering students who have an excellent performance in their bachelor studies are eligible for this scholarship', 'Full tuition fees of the regular study period for the respective master’s degree programme (within the regular study duration) depending on the admitted programme (excluding an administrative fee of 500 Euro per semester).', 'https://www.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=10000422', 'international\r', 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('S.N. Bose Scholars Program', ' The S.N. Bose Scholars Program provides an opportunity to Indian students (currently enrolled in a Bachelors or Masters degree in Atmospheric and Earth Sciences; Chemical Sciences; Engineering; Mathematical and Computational Sciences; and Physical Sciences).', 'Undertake research at the various US Universities in the summer for a period of 10-12 weeks.', 'http://iusstf.org/cms/newsimages/file/bose/SNBoseScholarsProgram2018.pdf', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Samsung Star Scholarship', 'Samsung Star Scholar program - to foster outstanding academic excellence of Jawahar Navodaya Vidyalaya students who gain admissions at IITs & NITs. The scholarship application is open for first year students in B. Tech/Dual Degree (B.Tech + M.Tech) course. Also, the students who were awarded with the Samsung Star Scholarship last year can renew their scholarship for the second year based on their overall academic performance.', 'Each student will be eligible for a scholarship support of Rupees Two Lakh, annually, for expenses related to annual tuition fee, hostel or mess charges.', 'http://www.samsung.com/in/microsite/sapne-hue-bade/star-scholar', 'First year students / miscellaneous \r', 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Scholarship from Karnataka Govt', 'Should be studying in India\'s prestigious institutions such as \"IITs, IIMs, NITs etc.', 'INR \"2 Lakh scholarship\"', 'http://backwardclasses.kar.nic.in/BCWDTraningOnlineIITIIMIISC.aspx', 'State + Minority \r', 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1),
('Scholarship from Uttarakhand Government', 'Refer to the website for further details ', 'Refer to the website for further details ', 'http://uktech.ac.in', 'State \r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1),
('Scholarship program by Mahabir Prasad Singh Foundation for Education and Research', 'Refer to the website for further details ', 'Refer to the website for further details ', 'www.mpsfer.in', 'Minority\r', 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Scholarship program GKS for Undergraduate School ', 'Refer to the website for further details ', 'Refer to the website for further details ', 'http://eng.kumoh.ac.kr/e_new/', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Semester exchange program in Alianza Universidas', 'Refer to the website for further details ', 'Refer to the website for further details ', 'http://alliance4universities.eu/en/mobility-scholarships/', 'international\r', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Special Scholarship Program of Kochi University of Technology Japan', 'KUT’s Special Scholarship Program (SSP) which is a 3-year English-medium doctoral program.', 'The Special Scholarship Program is a 3-year English-medium doctoral program designed for highly capable doctoral students. Successful applicants are entitled to receive following benefits: 1. Exempted from all the required student fees 2. 150,000 yen per month for research project work 3. 150,000 yen for travel and initial living cost (given only to international applicants who are living outside Japan)', 'https://www.kochi-tech.ac.jp/english/admission/ssp_til19apr/outline_1.html', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Special Scolarship Program by Kochi University of technology', 'Refer to the website for further details \nRefer to the website for further details ', 'A 3-year English-medium doctoral program offered by Kochi University of Technology, Japan\nRefer to the website for further details ', 'https://www.kochi-tech.ac.jp/english/admission/ssp/guideline.html (for April 2019)\nhttps://www.kochi-tech.ac.jp/english/admission/ssp_aft19oct/ssp_application_guideline.html', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('SRISTI Summer School on inclusive innovation', 'Refer to the website for further details ', 'Refer to the website for further details ', 'http://summerschool.sristi.org/apply', '\r', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Stipendium Hungaricum scholarship program of the Hungarian government', 'Refer to the website for further details ', 'Refer to the website for further details ', 'https://apply.stipendiumhungaricum.hu/', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Summer program with Nazarbayev University, Kazakhstan under Asian Universities Alliance (AUA)', 'Refer to the website for further details ', 'Financial aid provided to studentsProgram fee\nAccommodation, meals, and local transportation (including pick up and drop off at the airport)\n500 USD per person reimbursement for travel (to be claimed after reaching NU)\nProgram fee\nAccommodation, meals (excluding dinner), and local transportation (including pick up and drop off at the airport)\nProgram fee\nAccommodation, meals, and local transportation (including pick up and drop off at the airport)', 'Apply through IITB', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Summer research program in National Tsing Hua University', 'Refer to the website for further details ', 'Global Engineer Leadership (GEL) scholarship with subsidized round trip airline tickets up to NTD 15,000 and free accommodation at university residence hall.', 'http://eng-en.web.nthu.edu.tw/files/11-1130-3215.php', 'international\r', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Summer WASHU', 'Refer to the website for further details ', 'A competitive $2500 scholarship to qualified applicants; those who need additional support should indicate this in their application.', 'https://summerschool.wustl.edu/', 'international\r', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Swiss Government Excellence Scholarships', 'Refer to the website for further details ', 'Refer to the website for further details ', 'http://www.sbfi.admin.ch/scholarships_eng', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('TEL Aviv summer fellowship programme', 'This program is open to undergraduates who have a grade point average of 80% (3.0/4.0 scale) and above', 'Refer to the website for further details ', 'https://international.tau.ac.il/Summer_Internship_Program/?id=term-2', 'international\r', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('The Knight-Hennessy Scholars program, Stanford University', 'The Knight-Hennessy Scholars program is a new graduate-level scholarship aimed at preparing the next generation of global leaders to address the increasingly complex challenges facing the world.', ' Starting in fall 2018, Knight-Hennessy Scholars will annually select up to 100 high-achieving students with demonstrated leadership and civic commitment, who will receive full funding to pursue a graduate education at Stanford. Scholars may pursue studies at any of university’s seven internationally top-ranked graduate schools, and will be educated to navigate across business, government, academia, and the nonprofit sectors.', 'https://knight-hennessy.stanford.edu/', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('The Tower Research Capital India', 'Discipline: B.Tech., of Computer Science and Engineering, Electronics and Electrical Communications Engineering, and M.Sc., in Maths and Computing\nCGPA: Minimum 8.5 at the end of 2nd and 3rd years as the case may be\nOpen for students in 2nd or 3rd year.', 'The scholarship will be paid as reimbursement of tuition fees and other charges of hostel, mess etc ‘maximum upto Rs. 2 lakh.\nAn additional bookgrant of Rs. 20,000/- will be awarded.', 'none', 'international', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('ThinkSwiss Asia-Pacific scholarship program', 'Refer to the website for further details ', 'Refer to the website for further details ', 'https://euraxess.ec.europa.eu/worldwide/india/thinkswiss-asia-pacific-scholarship-program', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('ThinkSwiss Research Scholarships', 'Masters students or undergraduate students who completed 2nd year, currently enrolled in an Indian university or institute. The scholarship is open to students in all fields. Has a written confirmation from a Professor at a Swiss university that he/she will accept you for a research stay in his/her group', 'Refer to the website for further details ', 'https://www.swissnexindia.org/thinkswiss/', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Tsinghua University Scholarship', 'Should be applying for post graduation at the Tsinghua University', 'Refer to the website for further details', 'https://goo.gl/uyPXio', 'international\r', 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('University of Luxemburg', 'Refer to the website for further details ', 'PhD research stay opportunity for maximum 3 months in the the University of Luxembourg. University of Luxembourg will be providing scholarship (a monthly grant of 500€) as well as housing in a student residence and tuition fees waived.', 'Refer to the website for further details ', 'international\r', 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('USIEF Fellowships for Indian Citizens: 2019-2020', 'Refer to the website for further details ', 'Refer to the website for further details ', 'www.mhrd.gov.in/scholarships', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('Yale School of Management\'s Silver Scholars Program', 'The Silver Scholars Program was specifically designed for college seniors who wish to earn an MBA immediately after completing their undergraduate studies. Students enroll in the full-time two-year MBA program but rather than the traditional summer MBA internship, Silver Scholars complete a year-long internship of their choice. Candidates of all majors are welcome to apply.', 'Refer to the website for further details ', 'https://drive.google.com/open?id=0B6JFDFGZn7RDd3hIbTJTU0tocWdJQVZ5WWQtT1BpemdURXdN                         https://drive.google.com/open?id=0B6JFDFGZn7RDZDJPUVZRWk1TWmU3VVJCOGUwak5hbzNTYUg4', 'international\r', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
('​​TATA scholarship', 'SC/ST Girls students pursuing professional Education (Engineering, Medical and other suitable courses).', 'Refer to the website for further details ', 'http://www.faeaindia.org', 'SC/ST + girls \r', 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `scholarship_portal2020_db`
--
ALTER TABLE `scholarship_portal2020_db`
  ADD PRIMARY KEY (`name`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
